name: Cmake action & tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
<<<<<<< HEAD
    - name: Building all subprojects
      run: .\.github\workflows\buildScript.bat
    - name: Testing all subprojects
      run: .\.github\workflows\testScript.bat
=======
    - name: Building
      run: cd OSLab1 && cmake -S . -B build && cmake --build build
    - name: Running tests
      run: cd OSLab1 && cd build && ctest
>>>>>>> 34b347577d263efed2ab491f54d5c0717c3f8bcf

