name: Cmake action & tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Building all subprojects
      run: .\.github\workflows\buildScript.bat
    - name: Testing all subprojects
      run: .\.github\workflows\testScript.bat

