name: Cmake action & tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: L1
    - run: cd OSLab1
    - name: Building build files
      run: cmake -S . -B build
    - name: Building
      run: cmake --build build
    - name: Running
      run: cd build && ctest
