name: Cmake action & tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Building
      run: cd OSLab1 && cmake -S . -B build && cmake --build build && cd build && ctest

